name: Deploy to AWS App Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest
    outputs:
      sha_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/cromoswap:${{ steps.vars.outputs.sha_short }} .
          docker tag ${{ steps.login-ecr.outputs.registry }}/cromoswap:${{ steps.vars.outputs.sha_short }} ${{ steps.login-ecr.outputs.registry }}/cromoswap:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/cromoswap:${{ steps.vars.outputs.sha_short }}
          docker push ${{ steps.login-ecr.outputs.registry }}/cromoswap:latest

  deploy:
    name: Deploy to App Runner
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger App Runner Update
        run: |
          aws apprunner start-deployment --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }} --region us-east-1